//
// Fermentation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Fermentation: Codable { 


    public var temp: ValueUnit?

    public init(temp: ValueUnit?) {
        self.temp = temp
    }

}
