//
// Malt.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Malt: Codable { 


    public var name: String?
    public var amount: ValueUnit?

    public init(name: String?, amount: ValueUnit?) {
        self.name = name
        self.amount = amount
    }

}
