//
// MashTemp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MashTemp: Codable { 


    public var temp: ValueUnit?
    public var duartion: Double?

    public init(temp: ValueUnit?, duartion: Double?) {
        self.temp = temp
        self.duartion = duartion
    }

}
