//
// ValueUnit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ValueUnit: Codable { 


    public var value: Float?
    public var unit: String?

    public init(value: Float?, unit: String?) {
        self.value = value
        self.unit = unit
    }

}
